# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class AuraTrackerGcp < Formula
  desc "MCP server exposing GCP infrastructure operations as LLM-callable tools."
  homepage "https://github.com/asbrodova/aura-tracker-gcp"
  version "0.1.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/asbrodova/aura-tracker-gcp/releases/download/v0.1.0/aura-tracker-gcp_darwin_amd64.tar.gz"
      sha256 "dc32c2333ae8bcc93a19190104f60acb8678dee2d458f6b1f304c3eb2977e334"

      define_method(:install) do
        bin.install "aura-tracker-gcp"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/asbrodova/aura-tracker-gcp/releases/download/v0.1.0/aura-tracker-gcp_darwin_arm64.tar.gz"
      sha256 "d47a040cf13226d3db88062936991d708baaa53ee69dde5be3e44a5ff4bc63dc"

      define_method(:install) do
        bin.install "aura-tracker-gcp"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/asbrodova/aura-tracker-gcp/releases/download/v0.1.0/aura-tracker-gcp_linux_amd64.tar.gz"
      sha256 "473e84e89ba9e0ce67e87af474e391b16d724681e2e7684136284d7d2c54f3a9"
      define_method(:install) do
        bin.install "aura-tracker-gcp"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/asbrodova/aura-tracker-gcp/releases/download/v0.1.0/aura-tracker-gcp_linux_arm64.tar.gz"
      sha256 "7c3e3ba5af93433d50e733314b5ee17fb80dc956d6150d1f132b24acd430b20e"
      define_method(:install) do
        bin.install "aura-tracker-gcp"
      end
    end
  end

  test do
    system "#{bin}/aura-tracker-gcp", "--version"
  end
end
